### ISSUE TITLE
bug in buildingview

### ISSUE THREAD

**Issue by laurens-dg** [oSoc14/Artoria#18]
A nullpointer crashes the app. This is probably because the buildings don't get loaded in time.

Stacktrace:
ava.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at be.artoria.belfortapp.activities.MonumentDetailActivity.initGui(MonumentDetailActivity.java:88)

**Comment by laurens-dg** [comment]
Underlying cause; information only gets downloaded once every half day, so it should get put into the database.
